import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./components/SideBar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "JoeGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head />
      <body>
        < SessionProvider />
       <div className="flex">
        <div className="bg-[#bea060] max-w-xs h-screen overflow-y-auto md:min-w-[20rem}">
        <SideBar />
        </div>

  {/*ClientProvider - notification */}

     <div className="bg-black flex-1">{children}</div>
    </div>
   </body>
  </html>
);
}
