import type { Metadata } from "next";
import "./globals.css";
import SideBar from "../../components/SideBar";

export const metadata: Metadata = {
  title: "JoeGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head />
      <body>
     <div className="flex">
  {/* Sidebar */}
  <SideBar />

  {/*ClientProvider - notification */}


        <div className="bg-black flex-1">{children}</div>
        </div>
        </body>
    </html>
  );
}
